### ISSUE TITLE
Support for Clips

### ISSUE THREAD

**Issue by Franiac** [Franiac/TwitchLeecher#174]

**Comment by Franiac** [comment]
It seems like the info (JSON) for a clip is retrieved from

https://clips.twitch.tv/api/v2/clips/[slug]

Basically it contains only metadata. Important thing to note is that a clip is NOT a separate VOD with its own m3u8 playlist but a link to a part of an original VOD. In the JSON metadata of a clip there is the VOD id, the start position of the clip in that VOD and the duration. This way TL could do "auto-cropping" on the VOD in order to download only the clip part. On the UI side the cropping controls have to be disabled if the video to download is a clip.

A JSON response for a clip looks like this:

``` JSON
{
   "broadcaster_channel_url":"https://www.twitch.tv/lobosjr",
   "broadcaster_display_name":"LobosJR",
   "broadcaster_id":"28640725",
   "broadcaster_login":"lobosjr",
   "broadcaster_logo":"https://static-cdn.jtvnw.net/jtv_user_pictures/lobosjr-profile_image-b5e3a6c3556aed54-150x150.png",
   "broadcast_id":"26084918144",
   "curator_channel_url":"https://www.twitch.tv/inactive_gaming",
   "curator_display_name":"inactive_gaming",
   "curator_id":"30252976",
   "curator_login":"inactive_gaming",
   "curator_logo":"https://static-cdn.jtvnw.net/jtv_user_pictures/inactive_gaming-profile_image-94a28a7f1097e9c5-150x150.jpeg",
   "preview_image":"https://clips-media-assets.twitch.tv/26084918144-offset-21947-20.083333333333336-preview.jpg",
   "thumbnails":{
      "medium":"https://clips-media-assets.twitch.tv/26084918144-offset-21947-20.083333333333336-preview-480x272.jpg",
      "small":"https://clips-media-assets.twitch.tv/26084918144-offset-21947-20.083333333333336-preview-260x147.jpg",
      "tiny":"https://clips-media-assets.twitch.tv/26084918144-offset-21947-20.083333333333336-preview-86x45.jpg"
   },
   "game":"Path of Exile",
   "created_at":"2017-08-23T22:51:59Z",
   "title":"PoE New Player! Hardcore? | !hair | !schedule | !humble",
   "language":"en",
   "url":"https://clips.twitch.tv/ChillyMushyButterOhMyDog",
   "info_url":"https://clips.twitch.tv/api/v2/clips/ChillyMushyButterOhMyDog",
   "status_url":"https://clips.twitch.tv/api/v2/clips/ChillyMushyButterOhMyDog/status",
   "vod_id":"169206578",
   "vod_url":"https://www.twitch.tv/videos/169206578?t=6h5m47s",
   "vod_offset":21947,
   "embed_url":"https://clips.twitch.tv/embed?clip=ChillyMushyButterOhMyDog",
   "embed_html":"<iframe src='https://clips.twitch.tv/embed?clip=ChillyMushyButterOhMyDog' width='640' height='360' frameborder='0' scrolling='no' allowfullscreen='true'></iframe>",
   "view_url":"https://clips.twitch.tv/api/v2/clips/ChillyMushyButterOhMyDog/view",
   "id":"118297960",
   "slug":"ChillyMushyButterOhMyDog",
   "duration":20.083984,
   "views":126
}
```

**Comment by ElPumpo** [comment]
This is rather easy to implement, just get the status url of the Clip and choose the correct `quality`, then download the `source` as it contains a url of the entire clip saved in a mp4 format.

**Comment by Franiac** [comment]
Maybe you want to search for clips on a channel? Maybe filter by date? Maybe the current downloader is programmed towards VOD playlists and not clips. Maybe clips have a total different API than VODs and need to be implemented separately? Please let me decide what is easy to implement.

**Comment by ElPumpo** [comment]
ok

**Comment by Octoshape** [comment]
@Franiac are you still working on this project? I might look into contributing for some of the enhancements. Just wanted to make sure that I'm not submitting PRs to a dead project :)

**Comment by Franiac** [comment]
@Octoshape I am building a house at the moment. I am very busy doing so. That's the only reason why I didn't make any commits for the past 3 months. I simply don't have time. The project is 100% alive and as you can see I respond to every issue daily.

But before you start contributing, consider mailing me about what you want to do so we can create a solution that fits future plans of TL. The v5 API is deprecated and will be removed at the end of 2018 and the new API does not provide as much info as v5 does (video resolutions, fps and such). I hope this will change soon since the new Helix API is only a couple weeks old and not as refined as v5.

Just want to make sure, there's no surprise in the PR and we need to fix stuff, when it's done. Big thanks for your will to contribute!

**Comment by Octoshape** [comment]
@Franiac Alright, yeah let's continue this via e-mail. I am currently on vacation anyways until mid-January, so I'll contact you once I'm back.

**Comment by omkelderman** [comment]
I was looking for this feature and found out its literally one of the easiest things possible. On a clip page you can just right-click and save video.

Nonetheless would be cool to include it in the program, and a way to do it I found is as follows:
* get clip-info using https://dev.twitch.tv/docs/api/reference#get-clip
* take the thumbnail url (so `https://clips-media-assets.twitch.tv/157589949-preview-480x272.jpg` in the example on that page)
* remove everything after the number and add `.mp4`, so `https://clips-media-assets.twitch.tv/157589949.mp4`
* download that
* done

**Comment by daevski** [comment]
omkelderman is correct with his description. I've just implemented this method to batch download clips in a python script that I've forked on my account. Perhaps the API will soon make this better, but if not, this is an option even if it is hacky.

**Comment by Franiac** [comment]
@daevski I have found various clips where the url is different to the thumbnail url, so the approach of @omkelderman is not valid for every clip. But there is a url in the API response where "you can watch the clip". If there is an url, there is a possibility to download what you can watch.

I am still waiting for the new API to develop. Twitch is far from done with it. The main problem is still the fact, that video responses do not contain qualities and fps values anymore, so the quality selection would be gone with Helix.

**Comment by daevski** [comment]
I haven’t run into any clips that are different yet, but I’ll keep that in mind. 

I think as this year progresses I might watch this code base - I didn’t know this project was open and I love it! Hanks for the feedback 👍🏼

**Comment by LevelPulse** [comment]
Will we see clip integration anytime soon?

**Comment by Heistergand** [comment]
🙏

**Comment by alexandremix** [comment]
Just downloaded this software specifically to download my clips in batch, it does not have this function. 

Does anyone know if this is possible or if there's some alternative? Like another software?

**Comment by garoto** [comment]
> Does anyone know if this is possible or if there's some alternative? Like another software?

`youtube-dl` here on github.

**Comment by daevski** [comment]
> Does anyone know if this is possible or if there's some alternative? Like another software?

@alexandremix this is also an option that pulls from clips.twitch.tv: [Twitch-Batch-Loader](https://github.com/amiechen/twitch-batch-loader)

**Comment by benlanben** [comment]
> Important thing to note is that a clip is NOT a separate VOD with its own m3u8 playlist but a link to a part of an original VOD.

So if there is a clip from it can we access to the original VOD that's been outdated from a channel maybe for years?

**Comment by alexandremix** [comment]
You can now directly download Clips from the clip page on twitch, and you can also use a chrome extension to have download clips directly in the clips page. without having to open each one individually . 

I just use leecher to download Highlights or Entire Vods.

At least theres a solution to everything that I need. 

There's only one issue, Vods have VFR, and it causes issues when using the vod in premiere or any video editor, the video and audio gets desynced. Since leecher can't fix this I have to use handbrake to convert the video to a CFR Footage. 

Would love if you could download and Convert on the go.

**Comment by Washiii** [comment]
> 
> 
> @daevski I have found various clips where the url is different to the thumbnail url, so the approach of @omkelderman is not valid for every clip.

I worked as a video editor for some streamer/YouTubers some time, and that's true, I would get the url for the clip by inspecting the page, and sometimes the clip will have some resolution stuff upfront the file name (i.e. 720_157589949.mp4) it was a while back tho and it wasn't like that, it had some more text and specifications.

Idk how the API works now, but I'm really waiting for this feature to be released, and would be also good to get the list of clips directly from the program, just by giving the channel name.

**Comment by androng** [comment]
I would also like this function to be added

**Comment by androng** [comment]
I found the workaround is to click "Watch full video" button and then place the timecode into Twitch Leecher
![Screenshot 2022-06-11 005610](https://user-images.githubusercontent.com/605932/173179059-0a698956-302b-42da-8577-bceea23f707e.png)

**Comment by Franiac** [comment]
#803
